[book]
authors = ["tradam"]
language = "en"
multilingual = false
src = "src"
title = "Plore Tabletop Roleplaying Game"

[output.html.fold]
enable = true
level = 1

[output.html]
theme = "my-theme"
default-theme = "rust"
preferred-dark-theme = "rust"

[output.html.search]
enable = true

#[preprocessor.toc]
#command = "mdbook-toc"
#renderer = ["html"]
